import { ImageResponse } from 'next/og';
import { OG_IMAGE_SIZE } from './og';

/**
 * The default social-share card, shared by every Studio route segment.
 *
 * Generated by `next/og` (part of Next — no extra dependency, no binary to
 * keep in sync with the brand). It reproduces the reference banner: burgundy
 * ground, cream condensed wordmark, spaced-caps strapline, italic tagline, and
 * the ring cropped off the right edge.
 *
 * Served from `GET /og` (`src/app/(studio)/og/route.tsx`) rather than through
 * Next's `opengraph-image` file convention: that convention is per route
 * segment, does not cascade, and Turbopack rejects one placed inside a
 * catch-all segment — which is where nearly every CMS page is served from.
 *
 * A page overrides it by setting an OG image in the CMS: `buildPageMetadata()`
 * then emits `openGraph.images` explicitly and this is not used.
 */

const BURGUNDY = '#3e1420';
const RING = '#481e28';
const CREAM = '#edd5b9';
const ROSE = '#c19e8b';
const MAUVE = '#8c6a5a';

export function renderDefaultOgImage(): ImageResponse {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          position: 'relative',
          background: BURGUNDY,
          padding: '80px',
          fontFamily: 'sans-serif',
        }}
      >
        {/* The ring motif, cropped off the right edge. */}
        <div
          style={{
            position: 'absolute',
            top: -120,
            right: -220,
            width: 700,
            height: 700,
            borderRadius: 350,
            border: `56px solid ${RING}`,
          }}
        />

        <div
          style={{
            display: 'flex',
            fontSize: 26,
            letterSpacing: 10,
            textTransform: 'uppercase',
            color: MAUVE,
            borderTop: `2px solid ${MAUVE}`,
            paddingTop: 18,
            marginBottom: 28,
          }}
        >
          Professionele bikefit · Ninove
        </div>

        <div
          style={{
            display: 'flex',
            fontSize: 108,
            fontWeight: 800,
            lineHeight: 1,
            letterSpacing: -2,
            textTransform: 'uppercase',
            color: CREAM,
          }}
        >
          De Bikefit Studio
        </div>

        <div
          style={{
            display: 'flex',
            fontSize: 40,
            fontStyle: 'italic',
            color: ROSE,
            marginTop: 28,
          }}
        >
          Pijnvrij fietsen begint hier
        </div>
      </div>
    ),
    OG_IMAGE_SIZE,
  );
}
